apiVersion: v1
kind: Pod
metadata:
  name: ocpbugs-xxxx-remediation
  namespace: REPLACE_ME
  labels:
    hypershift.openshift.io/need-management-kas-access: "true"
spec: 
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hypershift.openshift.io/control-plane
            operator: In
            values:
            - "true"
        weight: 50
      - preference:
          matchExpressions:
          - key: hypershift.openshift.io/cluster
            operator: In
            values:
            - REPLACE_ME
        weight: 100
  containers:
  - image: REPLACE_ME
    imagePullPolicy: Always
    name: ocpbugs-xxxx-remediation
    env:
    - name: AWS_REGION
      value: REPLACE_ME
    - name: CLUSTER_ID
      value: REPLACE_ME
    - name: CLUSTER_NAMESPACE
      value: REPLACE_ME
    vaue:
    volumeMounts:
    - mountPath: /var/run/secrets/openshift/serviceaccount
      name: cloud-token
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true
    - mountPath: /.aws
      name: node-management-creds
  - args:
    - --service-account-namespace=kube-system
    - --service-account-name=capa-controller-manager
    - --token-audience=openshift
    - --token-file=/var/run/secrets/openshift/serviceaccount/token
    - --kubeconfig=/etc/kubernetes/kubeconfig
    command:
    - /usr/bin/control-plane-operator
    - token-minter
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d73b7e6779e5213bf5b2bad6cbe675528135e50437aae078ea57823e7d4b047e
    imagePullPolicy: IfNotPresent
    name: token-minter
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/openshift/serviceaccount
      name: cloud-token
    - mountPath: /etc/kubernetes
      name: kubeconfig
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true
  serviceAccount: capi-provider
  serviceAccountName: capi-provider
  volumes:
  - name: kubeconfig
    secret:
      defaultMode: 420
      secretName: service-network-admin-kubeconfig
  - name: node-management-creds
    secret:
      defaultMode: 420
      secretName: node-management-creds
  - emptyDir:
      medium: Memory
    name: cloud-token
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt